---
platform: linux

image_resource:
  type: docker-image
  source: { repository: adoptopenjdk/openjdk14, tag: jre14u-alpine-nightly }

inputs:
  - name: hello-world-src

outputs:
  - name: build

run:
  path: ./hello-world-src/sbt test dist