---
resources:
  - name: hello-world-src
    type: git
    source:
      branch: master
      uri: https://github.com/arshadalis/hello-world.git
      username: arshadalis
      password: ((password))

jobs:
  - name: build-hello-world
    plan:
      - get: hello-world-src
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: adoptopenjdk/openjdk14
              tag: jre14u-alpine-nightly
          inputs:
            - name: hello-world-src
          outputs:
            - name: artifact
          run:
            path: hello-world-src/sbt-dist/bin/sbt.sh
            args:
              - test
              - dist