---
resources:
  - name: hello-world-src
    type: git
    source:
      branch: master
      uri: https://github.com/arshadalis/hello-world.git
      username: arshadalis
      password: ((password))

jobs:
  - name: build-hello-world
    plan:
      - get: hello-world-src
        trigger: true
      - task: build
        file: hello-world-src/build.yml