---
resources:
  - name: hello-world-src
    type: git
    source:
      branch: master
      uri: https://github.com/arshadalis/hello-world.git
      username: arshadalis
      password: ((password))

jobs:
  - name: build-hello-world
    plan:
      - get: hello-world-src
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: hseeberger/scala-sbt
              tag: 8u141-jdk_2.12.3_1.0.2
          inputs:
            - name: hello-world-src

          run:
            path: hello-world-src/sbt-dist/bin/sbt
            args:
              - test
              - distZip